version: '3'
services:
  node1:
    build: .
    container_name: node1
    command: java MyApp client 1
    depends_on:
      - server
    networks:
      myapp:
        ipv4_address: 172.16.238.10
  node2:
    build: .
    container_name: node2
    command: java MyApp server 2
    depends_on:
      - server
    networks:
      myapp:
        ipv4_address: 172.16.238.11
  node3:
    build: .
    container_name: node3
    command: java MyApp server 3
    depends_on:
      - server
    networks:
      myapp:
        ipv4_address: 172.16.238.12
  node4:
    build: .
    container_name: node4
    command: java MyApp server 4
    depends_on:
      - server
    networks:
      myapp:
        ipv4_address: 172.16.238.13
  server:
    build: .
    container_name: server
    command: java MyApp server 1
    networks:
      myapp:
        ipv4_address: 172.16.238.9
networks:
  myapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
