version: '3'
services:
  city1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    command: bash -c "sleep 2 && java TSPParallelBFS && ip addr show eth0 | grep 'inet '"
  city2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    command: bash -c "sleep 2 && java TSPParallelBFS && ip addr show eth0 | grep 'inet '"
  city3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
    command: bash -c "sleep 2 && java TSPParallelBFS && ip addr show eth0 | grep 'inet '"
  city4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5004:5004'
    command: bash -c "sleep 2 && java TSPParallelBFS && ip addr show eth0 | grep 'inet '"
